import type { Metadata } from "next";
import { Barlow, Barlow_Condensed, Bellefair  } from "next/font/google";
import "./globals.css";


const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["400", "700"], // optional: specify weights you want
  variable: "--font-barlow-condensed",
});

const bellefair = Bellefair({
  subsets: ["latin"],
  weight: "400", // Bellefair usually has just one weight
  variable: "--font-bellefair",
});

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional: specify weights you want
  variable: "--font-barlow",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlowCondensed.variable} ${bellefair.variable} ${barlow.variable}`}>
        {children}
      </body>
    </html>
  );
}
